### ISSUE TITLE
[Bug]: ABS Search by Tag failes due to not locked ExpressionPartLbl and wrong translation

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/BCApps#1065]
### Describe the issue

When running the client in german language searching for files by tag failes with the following error message:

> Es konnten keine Blobs nach Tags gefunden werden..\\Antwortcode: 400 Error parsing query at or near character position 1: unexpected 'â'

the cause of the problem is that the ExpressionPartLbl is not locked and was translated with localized quotation marks.
https://github.com/microsoft/BCApps/blob/2704be1ea127c79cc22d439ad43919ef4a082e69/src/System%20Application/App/Azure%20Blob%20Services%20API/src/Helper/ABSFormatHelper.Codeunit.al#L168
![image](https://github.com/microsoft/BCApps/assets/18051656/78c4f71e-9296-4f51-8d15-603d516664b2)
xlf src: https://raw.githubusercontent.com/StefanMaron/MSDyn365BC.Code.History/master/system%20application/source/System%20Application/Translations/System%20Application.de-DE.xlf

### Expected behavior

works in all languages

### Steps to reproduce

implement a solution that search files by tags, change language to german

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
Uh, nice catch. Approved of course.
