### ISSUE TITLE
[BC Idea]: Client Credentials Authentication via Certificate+Password for Microsoft Graph Module + RestClient

### ISSUE THREAD

**Issue by pri-kise** [microsoft/BCApps#1093]
### BC Idea Link

https://experience.dynamics.com/ideas/idea/?ideaid=ffb44351-ee10-ef11-9899-000d3ae29eff

### Description

We should be able to use ClientCredentials Flow with Certificate+Password .

### I will provide the implementation for this BC Idea

- [X] I will provide the implementation for this BC Idea
Internal work item: [AB#534910](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/534910)

**Comment by mfalk118** [comment]
Will this also apply to SMTP email sending?
