### ISSUE TITLE
Adding Azure Search parameters to the payload in the AOAI Chat 

### ISSUE THREAD

**Issue by joergrau** [microsoft/BCApps#1178]
### Describe the issue

Small product enhancement:
The Codeunit "AOAI Chat Completion Params" uses the Codeunit "AOAI Chat Compl Params Impl", which adds parameters to the payload:
procedure AddChatCompletionsParametersToPayload(var Payload: JsonObject)
begin
if GetMaxTokens() > 0 then
Payload.Add('max_tokens', GetMaxTokens());
Payload.Add('temperature', GetTemperature());
Payload.Add('presence_penalty', GetPresencePenalty());
Payload.Add('frequency_penalty', GetFrequencyPenalty());
end;

 
There is currently no option to specify Azure Search parameters. The parameters I would like to add are:
"azureSearchEndpoint" 
"azureSearchKey"
"azureSearchIndexName"

### Expected behavior

Adding additional procedures to set and get the new Azure Seach parameters. Adding the parameters to the payload if they were set.

### Steps to reproduce

Currently no procedures available to set the Azure Search parameters.

### Additional context

As discussed on the yammer group: https://www.yammer.com/dynamicsnavdev/#/threads/inGroup?type=in_group&feedId=132956700672&view=all

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by darjoo** [comment]
Hi @joergrau, this is something we'd accept :) 
I need a bit more clarification about your implementation. Is this purely just adding the parameters to enable the it to perform Azure AI Search or would there be additions to the API/Objects that make it easier to work with the information returned as well?

-Darrick

**Comment by joergrau** [comment]
Hi @darjoo,
It is for adding more procedures for set/get the three parameters and adding them to the payload like this:

```
procedure AddChatCompletionsParametersToPayload(var Payload: JsonObject)
    begin
        if GetMaxTokens() > 0 then
            Payload.Add('max_tokens', GetMaxTokens());

        Payload.Add('temperature', GetTemperature());
        Payload.Add('presence_penalty', GetPresencePenalty());
        Payload.Add('frequency_penalty', GetFrequencyPenalty());

        if IsJsonMode() then
            Payload.Add('response_format', GetJsonResponseFormat());

        if GetAzureSearchEndpoint() <> '' then
            Payload.Add('azureSearchEndpoint', GetAzureSearchEndpoint());
        if GetAzureSearchKey() <> '' then
            Payload.Add('azureSearchKey', GetAzureSearchKey());
        if GetAzureSearchIndexName() <> '' then
            Payload.Add('azureSearchIndexName', GetAzureSearchIndexName());
    end;
```
 
So, following the same way as for the other parameters, e.g. temperature

**Comment by darjoo** [comment]
@joergrau
Just adding those parameters do not seem correct though. I have not tested and only reviewed the documentation and API specs.
It seems like it should be added through the DataSource key, with a specific type etc. 

https://learn.microsoft.com/en-us/azure/ai-services/openai/references/on-your-data?tabs=python#data-source
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/stable/2024-02-01/inference.json

And even once that works, it would be better for all if we can work together to design how the output can be worked with. For example with Operation Response/Function Response. Otherwise, everyone who uses this will have to develop their own parsing mechanism which makes little sense when it should be part of the AI module.

**Comment by joergrau** [comment]
@darjoo I already did the coding as it is not much work. However, I struggle to get this tested as I can't do any testing around AI in a Docker container. I tried to follow the process explained here LOCAL_DEV_ENV.md  get an error message: 
![image](https://github.com/microsoft/BCApps/assets/6723135/2bffd85d-0576-4e94-bb1a-9dfd6a9d0cca)

when running the NewDevEnv.ps1 script.

What is the best way to deploy this updated System App and to try it out?

**Comment by JesperSchulz** [comment]
@mazhelez / @aholstrup1, could you look into the script issue?

**Comment by mazhelez** [comment]
@joergrau I see codeunit "Library - Password" was added recently. Are you maybe not running against the latest code or latest artifact?

**Comment by joergrau** [comment]
@mazhelez I synced my fork and updated my branch, but I got the same error.

**Comment by JesperSchulz** [comment]
@darjoo / @joergrau, where are we on this one?

**Comment by joergrau** [comment]
@JesperSchulz I'm waiting for your assistance. Alternatively, please advise on how I could deploy a new system app to test AI integration. The coding is done, I "just" need to test it.

**Comment by aholstrup1** [comment]
@joergrau we've made some updates to the NewDevEnv script recently. Can you try updating your branch with the latest changes from BCApps and try again? 

If you run `.\build\scripts\DevEnv\NewDevEnv.ps1 -ContainerName "BCAppsTest" -ProjectPaths '.\src\System Application\App\'` you should get a container with your new System App

**Comment by joergrau** [comment]
Thanks @aholstrup1 that worked. I can continue now and will let you know when done with a PR.

**Comment by joergrau** [comment]
> @joergrau Just adding those parameters do not seem correct though. I have not tested and only reviewed the documentation and API specs. It seems like it should be added through the DataSource key, with a specific type etc.
> 
> https://learn.microsoft.com/en-us/azure/ai-services/openai/references/on-your-data?tabs=python#data-source https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/stable/2024-02-01/inference.json
> 
> And even once that works, it would be better for all if we can work together to design how the output can be worked with. For example with Operation Response/Function Response. Otherwise, everyone who uses this will have to develop their own parsing mechanism which makes little sense when it should be part of the AI module.

@darjoo you are correct, just adding the three parameters is not the right approach. The data_sources key is required with an array of one or many data sources. As data sources can be of different types, I settled on adding a procedure where a developer can pass on the JsonArray for the data_soruces key. A data source can contain again many parameters and filter so it is getting too complex to cater for all types, and therefore it is more flexible when a developer passes on the JsonArray.

I added a new procedure in codeunit 7761 "AOAI Chat Completion Params"
`/// <summary>
    /// Sets the data_sources array in the payload. The data sources can be used to provide additional search data to the model.
    /// </summary>
    /// <param name="DataSourceArray">JsonArray to add parameters relevant for the data sources to be included.</param>
    procedure SetDataSourcesArrayToPayload(var DataSourcesArray: JsonArray)
    begin
        AOAIChatComplParamsImpl.SetDataSourcesArrayToPayload(DataSourcesArray);
    end;
`

If you want to include an Azure Search data source for example, then you can pass on your data source JsonArray like this as an example:

`local procedure AddAzureSearchParameters(var AOAIChatCompletionParams: Codeunit "AOAI Chat Completion Params")
    var
        DataSourceArray: JsonArray;
        DataSourceObject: JsonObject;
        DataSourceParametersObject: JsonObject;
        DataSourceAuthenticationObject: JsonObject;
        BlankJsonObject: JsonObject;
    begin
        DataSourceObject.Add('type', 'azure_search');

        DataSourceParametersObject.Add('endpoint', GetAzureSearchEndpoint());
        DataSourceParametersObject.Add('index_name', GetAzureSearchIndexName());
        DataSourceParametersObject.Add('semantic_configuration', 'default');
        DataSourceParametersObject.Add('query_type', 'simple');
        DataSourceParametersObject.Add('fields_mapping', BlankJsonObject);
        DataSourceParametersObject.Add('in_scope', 'true');
        DataSourceParametersObject.Add('role_information', '');
        //DataSourceParametersObject.Add('filter', ));
        DataSourceParametersObject.Add('strictness', 3);
        DataSourceParametersObject.Add('top_n_documents', 5);
        DataSourceAuthenticationObject.Add('type', 'api_key');
        DataSourceAuthenticationObject.Add('key', GetAzureSearchKey());
        DataSourceParametersObject.Add('authentication', DataSourceAuthenticationObject);
        DataSourceParametersObject.Add('key', GetAzureSearchKey());
        
        DataSourceObject.Add('parameters', DataSourceParametersObject);

        DataSourceArray.Add(DataSourceObject);
        
        AOAIChatCompletionParams.SetDataSourcesArrayToPayload(DataSourceArray);
    end;
`

**Comment by joergrau** [comment]
@darjoo, @JesperSchulz what are the next steps? I submitted a PR and documented the approach above.

**Comment by joergrau** [comment]
Hi @JesperSchulz, welcome back from your holidays. I will be leaving for my holidays today until the end of the month. Just in case you post a comment here and get no reply from me.

**Comment by JesperSchulz** [comment]
Then I will wish you a lovely vacation, @joergrau 🌞 While you're gone, we'll take a look at your PR!

**Comment by JesperSchulz** [comment]
Closing based on latest comment in linked pull request.
