### ISSUE TITLE
NoSeriesManagement - add var to handle obsolete No Series[Bug]: 

### ISSUE THREAD

**Issue by bussik** [microsoft/BCApps#1268]
### Describe the issue

On the previous versions of BC there was an event:
![image](https://github.com/microsoft/BCApps/assets/24941235/08618d24-374a-4163-9765-3e14b95336d7)

But now there is new event:
![image](https://github.com/microsoft/BCApps/assets/24941235/0196123d-ebb4-4899-8573-5b489da7d1e3)
And var is missing despite of that the function in body has a var.

### Expected behavior

NoSeriesLine should have var

### Steps to reproduce

Create document with No. Series set up.

### I will provide a fix for a bug

- [X] I will provide a fix for a bug
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/BCApps/pull/1267
```

**Comment by JesperSchulz** [comment]
@AndreasMoth, could you please triage this issue?

**Comment by grobyns** [comment]
@bussik please review the PR https://github.com/microsoft/BCApps/pull/1446

**Comment by bussik** [comment]
When can we expect fixes available to install? @JesperSchulz @grobyns

**Comment by aholstrup1** [comment]
@bussik hotfix is on the way :) We started rolling it out last week and will continue to roll it this week.

If you want to test it already now in a docker environment the fix should already be available in the latest artifacts.

`New-BcContainer -artifactUrl (Get-BCArtifactUrl -version 24.0 -select Latest -country W1) -accept_eula` 

Should create a container with the updated No Series module.
