### ISSUE TITLE
Validation error i AppSource when using extended field in No. Series table.

### ISSUE THREAD

**Issue by tomddlc** [microsoft/BCApps#1368]
Description:

I have two apps i AppSource. A base application and an extra module, which is dependent on the first app.

The base application adds a field called "Customer Templ. Code L365" to the standard table 308 No. Series. The module app uses this new field.

I released a new version of the module app two weeks ago without problems. But when I try to release an update today, I get an error from AppSource.

Diagnostic code AL0132
Diagnostic message: 'Record "No. Series"' does not contain a definition for 'Customer Templ. Code L365'
Validation request id: fea47eef-de76-4956-b7fa-2a84fdaa8279

I have not changed the table extension or the code accessing the extended field since the app last passed validation.

**Comment by JesperSchulz** [comment]
@kalberes, why was this issue transferred to the BCApps repository? This issue doesn't strike me as something @tomddlc can do anything about by himself through a pull request against the Business Foundation?
@tomddlc, maybe this should be a support case (aka.ms/bcsupport)? At least I don't think your issue will get much traction here ☹️
