### ISSUE TITLE
[Bug]: setting nextmarker in AFSFileClientImpl.codeunit results in an error if nothing is found 

### ISSUE THREAD

**Issue by Pieterheinevdm** [microsoft/BCApps#1409]
### Describe the issue

if NodeList is empty no temprecords are beiing inserted and an error will occur because of the modify on an not inserted temprecord

### Expected behavior

Nextmarker is always blank if nothing is found, so setting this is not needed

### Steps to reproduce

Make AFS return no result. For examply by setting Prefix to ABCDEFG a non existing file name.

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by SlavaGeorgiev** [comment]
created a fix rather there is no "Next Marker" or the table AFSDirectoryContent is empty.

**Comment by JesperSchulz** [comment]
@Pieterheinevdm / @SlavaGeorgiev, so which solution should I pick? Any preference?

**Comment by SlavaGeorgiev** [comment]
> @Pieterheinevdm / @SlavaGeorgiev, so which solution should I pick? Any preference?

Good question @JesperSchulz 

@Pieterheinevdm - his PR fixes the issue in case the EntryNo isn't equal to zero.
My PR avoids a modify if there is no NextMarker and the directory is empty. 

In case this helps.

**Comment by Pieterheinevdm** [comment]
both will do the job, my change is cleaner, but I won't mind which one you choose.
