### ISSUE TITLE
[Bug]: HttpContent.SetHeader failing when secret header already exists

### ISSUE THREAD

**Issue by vody** [microsoft/BCApps#1479]
### Describe the issue

The "Http Content" codeunit throws an error message when content is defined from SecretText.  
```
Error message: 
Cannot add value because the header 'Content-Type' does not support multiple values.

AL call stack: 
"Http Content Impl."(CodeUnit 2355).SetHeader line 12 - System Application by Microsoft
"Http Content Impl."(CodeUnit 2355).SetContentTypeHeader line 4 - System Application by Microsoft
"Http Content Impl."(CodeUnit 2355).SetContent line 6 - System Application by Microsoft
"Http Content"(CodeUnit 2354).SetContent line 2 - System Application by Microsoft
"Http Content"(CodeUnit 2354).Create line 2 - System Application by Microsoft\"Http Content"(CodeUnit 2354).Create line 2 - System Application by Microsoft
```
This happens because inside "Http Content Impl.".SetHeader procedure `Headers.Contains(Name)` condition will return false for a secret header, which will be automatically created when we set a content from the SecretText value. 

### Expected behavior

Content will be defined with a new header without error.

### Steps to reproduce

```
codeunit 50000 SetHeader
{
    trigger OnRun()
    var
        HttpContent: Codeunit "Http Content";
    begin
        HttpContent.Create(SecretStrSubstNo('anything'));
    end;
}
```

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
@ajkauffmann has agreed to include this in a pull request he is working on anyway 🥳
I cannot assign it to him (seems I can only assign to people who have been active on the issue), but consider it assigned 😉

**Comment by ajkauffmann** [comment]
I'm active now. 😊
Yes, happy to take this one!

**Comment by JesperSchulz** [comment]
And now I could assign you 🥳

**Comment by vody** [comment]
@ajkauffmann thank you for picking this one. We tried to use it internally to promote open-source contribution within an organization but it was pushed down in priority.

**Comment by tuschacht** [comment]
Is this issue fixed, because i have the same issue when i try to use a secretbody with Application/JSON as content-type

**Comment by ajkauffmann** [comment]
Yes, a PR will be created next week!

**Comment by tuschacht** [comment]
Thank you for the Solution, this is just a major issue because i have a Customer who needs this solution ASAP and security is key.

**Comment by ajkauffmann** [comment]
You can always use a workaround by creating a HttpContent object with the correct and use it with HttpContent.Create(HttpContent). Then you don't have to wait for the PR to be approved and backported to v25.
