### ISSUE TITLE
[Contribution Process Bug]: Improve implementation phone no. check

### ISSUE THREAD

**Issue by DonHendriksen** [microsoft/BCApps#1485]
### Describe the issue

This is a follow up on issue 767 which is reported in the BusinessCentralApps repo.

The request is to extend the validation on characters in phone no. to Contact Alt. Address fields phone no. and mobile phone no. In the BusinessCentralApps repo we started developing, but on request of Microsoft we moved the validation implementation to the System Application app. This work item is created so we are able to link the PR to it.

### Expected behavior

Similar validation check to 'Contact Alt. Address' because the value of contact alternative address is used to update the contact. This process shouldn't be blocked by incorrect input in the source data of contact alternative address.

### Steps to reproduce

- In BC navigate to a contact
- Open the card page
- Enter a phone no. with alphabetical characters
- Error will be thrown
- Resolve the error
- Then navigate in the ribbon to Related - Contact - Alternative Address - Card
- Add new record
- Enter a random value for Code
- Enter a phone no. with alphabetical characters
- No error is thrown

### Additional context

@JesperSchulz, please judge this issue.

**Comment by JesperSchulz** [comment]
Solution provided in BaseApp. Closing issue.
