### ISSUE TITLE
[BC Idea]: Unix Timestamp handling

### ISSUE THREAD

**Issue by Wildrik** [microsoft/BCApps#1809]
### BC Idea Link

https://experience.dynamics.com/ideas/idea/?ideaid=9f991316-73fd-ee11-a73c-6045bdb93e93

### Description

Creating a unix timestamp in AL code is usually pretty straightforward, but not when the code used by different client types. A webservice client is always in UTC and does not need any time zone corrections, while a web client session does. E.g.

```
OriginDateTime := System.CreateDateTime(DMY2Date(1, 1, 1970), 0T);
TimeZoneOffset := TimeZone.GetTimezoneOffset(OriginDateTime);
OriginDateTime := OriginDateTime + TimeZoneOffset;
exit((CurrentDateTime - OriginDateTime) div 1000)
```

We run into issues when a webservice client is started by a regular user (using authorization code grant flow). Such a user has a time zone offset, while the webservice client session is in UTC. The timestamp generated by code above would be off by the user timezone offset (that is actually only applicable to the web client). The client type can be determined using CurrentClientType(), but that doesn't help if you need a unix timestamp is in a background client that was created by either a web client or webservice client.

Idea: add a wrapper for the C# code below:

`DateTimeOffset.UtcNow.ToUnixTimeSeconds()`

This far more straightforward and always works, regardless of the client type.

I've suggested to add this to Type Helper in de Base App. However, @JesperSchulz suggested to add it to the System App instead. It could be added to the "Date and Time" component as a codeunit (facade/impl) that can handle various conversions between Unix timestamps and regular DateTime-variables.

### I will provide the implementation for this BC Idea

- [X] I will provide the implementation for this BC Idea

Fixes [AB#526024](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/526024)

**Comment by JesperSchulz** [comment]
Makes a lot of sense. Approved.
