### ISSUE TITLE
[BC Idea]: Base64 convert support for SecretText

### ISSUE THREAD

**Issue by TKapitan** [microsoft/BCApps#1855]
### BC Idea Link

https://experience.dynamics.com/ideas/idea/?ideaid=38052cce-d15f-ef11-a4e6-6045bdb4984c

### Description

We need a Base64 Converter to support SecretText. We implemented the secrettexts for our REST app that supports all authentication module, but we struggle with basic auth (mostly needed for OAuth2 code flow handshaking) as we can't generate the base64 for details stored in secrettext isolatedstorage. 

This method should return again secrettext as it just needs to be passed to httpheader as auth.

### I will provide the implementation for this BC Idea

- [X] I will provide the implementation for this BC Idea

**Comment by JesperSchulz** [comment]
Unfortunately we don't yet have an internal work item created for the BC Idea. If I don't have one tomorrow, I'll manually create one. But as such, the issue is approved!
