### ISSUE TITLE
[Bug]: Reasoning for Image Codeunit being limited to 5MB?

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/BCApps#1970]
### Describe the issue

[Originally started here](https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=2959960207736832).

[The following limit is implemented](https://github.com/microsoft/BCApps/blob/f591cf2931ed2df68a8b8066129ae9ffb1b059e4/src/System%20Application/App/Image/src/ImageImpl.Codeunit.al#L295).

This prevents processing larger images that may need to be cropped or altered in some fashion. This means we now have to make a request to an external service, process the return, etc., greatly increasing overhead and generally being slower, "locking" BC for more time.

### Expected behavior

Have the limit be configurable, removed, or higher.

### Steps to reproduce

pass in image that is larger than 5mb and get hit with error

### Additional context

typically we process labels of some sort from an external service, e.g. ucc labels, and some services will return all images in a single image we then need to split and process to store and print correctly. Because of this limit, we are unable to use the built in BC tools and instead have to rely on external services.

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

### Additional note

There may be a legitimate reason for the 5MB limit. This is more a hope that it can be changed in the future.

**Comment by JesperSchulz** [comment]
Asked internally if anyone remembers where that limit came from. Stay tuned!

**Comment by mjmatthiesen** [comment]
> No one remembers and I cannot find any reasoning. Hence approving issue.

Just want to clarify one thing: Does Microsoft still want a limit, or is no limit acceptable? I have a limit of 50MB in mind, but since I don't know the actual backend implication, if none is possible that would be "future proof" for us.

**Comment by mjmatthiesen** [comment]
> A limit is preferable. Uploading an image of several GB can derail the production system. 50MB sounds reasonable.

I'm too much of an idealist and assume people will play nice. Good point. I am out next week but will issue a PR when I come back. Thanks!

**Comment by mjmatthiesen** [comment]
Hi @JesperSchulz I am just wondering how I determine when this will be released. Right now base on the repo it will be 26.0, but I don't know if that app.json is "true"

**Comment by JesperSchulz** [comment]
By default the fix will release with the upcoming major. But if urgently needed, we can backport the fix for release with the upcoming minor (possibly 25.2, if we hurry up). Would you like that?
