### ISSUE TITLE
[Bug]: UpgradeTag does not have a procedure for database upgrade tags

### ISSUE THREAD

**Issue by TKapitan** [microsoft/BCApps#1978]
### Describe the issue

Codeunit 9999 "Upgrade Tag" does not have all procedures for database upgrade tags.the 

### Expected behavior

While we have 
- UpgradeTag.SetDatabaseUpgradeTag(TagName)

We don't have a corresponding procedure for HasDatabaseUpgradeTag. For this, developers must use HasUpgradeTag(TagName, '') to manually specify a blank company name.

While this is not challenging, it's hard to explain to new developers why we have a special Setter (as the SetUpgradeTag(TagName, '') would also work) but not for Getter.

### Steps to reproduce

-

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by pri-kise** [comment]
I recently stumbled over the same issue and this should really be improved.

**Comment by JesperSchulz** [comment]
Agree. Approved.
