### ISSUE TITLE
[Bug]: GetTableUrl in TableInformation Cache Impl. is wrong for Table with DataPerCompany=false (e.g. Tenant Media)

### ISSUE THREAD

**Issue by pri-kise** [microsoft/BCApps#2262]
### Describe the issue

The `Company Name` of cross company tables is populated with the string `(Cross-Company Data)`.
The problems is that the procedure `GetTableUrl` uses this placeholder string as  company name.

### Expected behavior

The url should be constructed  with the current company instead of the `(Cross-Company Data)` string.

### Steps to reproduce

Open the TableInformation Page and click on the a table that isn't company specific e.g. Tenant Media.

### I will provide a fix for a bug

- [x] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
Sounds fair. Approved.
