### ISSUE TITLE
[Bug]: Unnecessary variabl ShowLogo in Email Accounts Page

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/BCApps#2365]
### Describe the issue

As we have fixed it for:
https://github.com/microsoft/BCApps/pull/663

Variable Show Logo on Email Accounts page have no function:
![Image](https://github.com/user-attachments/assets/f8fad848-3d9f-44bc-9237-a1d4f3e6e27b)

![Image](https://github.com/user-attachments/assets/00a71b90-d8a8-4777-82fc-68a20258bbee)

It's always set to true.
We could do cleanup and remove it, behavior would stay same.

### Expected behavior

/

### Steps to reproduce

/

### I will provide a fix for a bug

- [x] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
Sure, let's do that.
