### ISSUE TITLE
[Bug]: Document Check factbox stopps working when logging more than one custom error via error message management

### ISSUE THREAD

**Issue by TobiDynDev** [microsoft/BCApps#2406]
### Describe the issue

When extending the Document Checks enabled via the Data Check field in the General Ledger Setup page with more than one error logged via the error message management the Factbox does not refresh anymore.
The issue just happens in case at least another check is logged already via the Error.Info.

### Expected behavior

To be able to extend the performed document checks with multiple error messages logged via the error message management.

### Steps to reproduce

- Enable the Data Check in General Ledger Setup
- Use the Document Check FactBox
- Create a new Purchase Order with a Vendor, a purchase line with an item and a quantity.
Now the document check should have one error: "You need to enter the document number of the document from the vendor in the Vendor Invoice No. field, so that this document stays linked to the original."

- Add code to the OnAfterCheckPurchDoc subscriber event of the Purch.-Post codeunit:
![Image](https://github.com/user-attachments/assets/41998e6c-0294-4d54-9471-229b883a3b31)
- It is not possible to Refresh the factbox anymore. With just the 1st. error the refresh is possible.

### Additional context

The issue is due to the GetErrors and CollectErrors procedures:
![Image](https://github.com/user-attachments/assets/4df9ed9d-03e9-499f-9d19-e76fb50fd195)

At the end of GetErrors happens a findfirst - and TempErrorMessage points to the first record
![Image](https://github.com/user-attachments/assets/c3050bf1-2662-4b1d-b726-7f5a2ac36712)

Within collecterrors, the record TempLineErrorMessage points to the first record and it is tried to Insert the by the base app generated errorinfo error with the same ID which was used to log the "2nd error message"
![Image](https://github.com/user-attachments/assets/c5a92a40-f22c-4b09-af76-43376ccef1f0)

### I will provide a fix for a bug

- [x] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
Sounds like a bug. Approved.

**Comment by TobiDynDev** [comment]
@JesperSchulz i just recognized that the error message management is not part of the system app - but it's part of the base app in the system folder.
I will close this issue and create a new one in the BusinessCentralApps repository
