### ISSUE TITLE
[Contribution Process Bug]: job Queue error message keep repeating the initial error

### ISSUE THREAD

**Issue by moulikaku** [microsoft/BCApps#2412]
### Describe the issue

Job Queue error message keep repeating the initial error

Whenever job queue fails it always shows the first error message

### Expected behavior

show latest error message

### Steps to reproduce

Hi everyone,

I recently found an issue about Job Queue error message. It can't log the real error message which caused wrong direction of error check.

For example, I create a Job Queue Entry to run this CU that must return error.
Suppose every error messages are different as I log the current datetime.

However, no matter how many times running this JQ Entry, it will only repeat the Error Message of initial run.

Only after I cleared the "Error Message Register Id", then I can log a new Error Message.

Is there any setup I miss to cause this?

Thanks to Leo chu for the content

![Image](https://github.com/user-attachments/assets/4301f89a-c7fd-41fc-8ea7-252bb4ccfa04)
![Image](https://github.com/user-attachments/assets/343634d6-56cc-4c62-b646-5b7856269075)

![Image](https://github.com/user-attachments/assets/1e37fe86-8c99-47ce-87f3-f464fc1407a5)

**Comment by JesperSchulz** [comment]
Thanks for reporting! We've got a fix coming 😊

As this issue isn't related to the System Application / Business Foundation, it shouldn't have been logged here. I'm hence closing this issue. But a fix will be shipped soon.
