### ISSUE TITLE
[Bug]: Job Planning Line To Calendar

### ISSUE THREAD

**Issue by KiprotichKelly** [microsoft/BCApps#2473]
### Describe the issue

When sending a job planning line to Calendar, it gets the resource no from the resource table using the project manager field on the job card. However, the project manager field on the job card looks up to the users table therefore bringing in some inconsistency.
![Image](https://github.com/user-attachments/assets/4c4683ca-d717-450d-9bb1-3bc2897a6852)
![Image](https://github.com/user-attachments/assets/5d908956-5388-4298-b549-a01fa4451285)

### Expected behavior

The get should get from the user setup table i.e.
![Image](https://github.com/user-attachments/assets/7b429f28-19a2-4588-8070-f84aae93f8bc)

### Steps to reproduce

On the job planning lines,  outlook tab, click "send to Calendar" action
![Image](https://github.com/user-attachments/assets/fd77fe70-4e40-49b1-83c1-b3e10c5ddbc5)
It will throw an error similar to this
![Image](https://github.com/user-attachments/assets/8c6e208d-eae0-476b-9c64-4733c16eed5f)

### I will provide a fix for a bug

- [x] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
That indeed sounds like a bug, but it in the BaseApp: App/Layers/W1/BaseApp/Projects/Project/Planning/JobPlanningLineCalendar.Codeunit.al

You'd have to suggest and fix this code in the BaseApp contribution pilot: https://github.com/microsoft/businesscentralapps. For access to the pilot, please fill out the following form: https://forms.office.com/r/E9wyE5a58f.

This repository is only for issues and improvements in the System Application or Business Foundation.

Would you like me to move the issue to the contribution pilot for you?

**Comment by KiprotichKelly** [comment]
Yes please.
Thank you

**Comment by sergeyol** [comment]
There is a bug on this already in BaseApp repo: https://github.com/microsoft/BusinessCentralApps/issues/790

**Comment by JesperSchulz** [comment]
> There is a bug on this already in BaseApp repo: [microsoft/BusinessCentralApps#790](https://github.com/microsoft/BusinessCentralApps/issues/790)

Which I can see has stranded... I'll try to get some traction on that one! This one I'll close as a duplicate then.
