### ISSUE TITLE
[Extensibility Bug]: Provide a possibility to set the Telemetry Logger Interface explicit instead of relying on a event subscriber on publisher

### ISSUE THREAD

**Issue by pri-kise** [microsoft/BCApps#298]
### Describe the issue

I'd like to have the possibility to explicit the the "Telemetry Logger" Interface, when using the Telemetry or FeatureTelemetry Codeunits.

Currently we need a subscriber in any of our apps (with identical publisher).
And since we don't know which app is installed we might subscribe multiple times to this event publisher, which results in an additional telemetry event, that I want to avoid.

### Expected behavior

it should be possible to explicit set the interface via a Setter Method on the Public Facade Codeunits.

or in other words:

it should be possible to set an TelemetryLogger Interface to skip the following lines 

```al
        TelemetryLoggers.SetCurrentPublisher(Publisher);
        TelemetryLoggers.OnRegisterTelemetryLogger();

        if TelemetryLoggers.GetTelemetryLogger(TelemetryLogger) then
```
https://github.com/microsoft/BCApps/blob/636c354bc6d2b27ba6527fd193ac494af7f8ebfa/src/System%20Application/App/Telemetry/src/Logging/TelemetryImpl.Codeunit.al#L41C1-L41C1

### Steps to reproduce

Create two apps with the same publisher and subscribe to the the TelemetryLogger Event.

### Additional context

I already talked to some people of microsoft at Directions EMEA 2023 and they suggested to open an issue for this topic to discuss here fruther with @IhorHandziuk who created this module.

**Comment by IhorHandziuk** [comment]
Hi @pri-kise, I think adding the ability to provide the telemetry logger implementation on a variable instance is not the best approach, as it will add more lines of code and potentially more confusion to something that is suppoused to be very siple to use.

Normally we recommend that partners extract the implementation of the telemetry logger in a separate app, and then add it as a dependency to the existing apps (see this [Viva Engage post](https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=2411336245280768)).
If this is not a viable option for some reason, we can also just remove the warning about having multiple telemetry logger implementations altogether (and assume that the extension developer is aware that a random imlementation will be picked).

**Comment by pri-kise** [comment]
I will discuss with my other collegaues internally and will close this issue until we have evaluated the best approach.

**Comment by JohnnyUndercover** [comment]
Why can't more than one interface be saved in the Telemetry Logger codeunit? (List of [interface] would be nice ;) )

And if there is an implementation for the current app, this will be used if not the one for the publisher. The register method might need an overload to specify whether the logger should be used for all apps of the publisher (default) or only for the current app.

In case I have misunderstood the task of this feature, I would be happy if someone could explain again how the feature should be used in the context of an ISV with multiple apps. What assumptions have been made?
Same Applicationsights endpoint for all apps? If so, are there any advantages that I am overlooking?
With separate endpoints I see the advantage that the limits etc. for the Application Insights workspace can be maintained individually for each app (with transformation rules it quickly becomes very complex).

**Comment by IhorHandziuk** [comment]
Hi @JohnnyUndercover, what you are describing indeed sounds like a good improvement to the telemetry module. Unfortunately, it's currently impossible to define a list of interfaces (the code wouldn't compile). We could define a number of individual variables to sort-of support this, but that's an antipattern we would like to avoid, especially if the gain is not that big.

**Comment by JesperSchulz** [comment]
@pri-kise, @JohnnyUndercover and @IhorHandziuk, where are we on this issue? Which changes (which actually can be done) are requested to be made? And can we approve those changes? This issue isn't fully fleshed out, it seems.

**Comment by JohnnyUndercover** [comment]
@IhorHandziuk @JesperSchulz Would it be possible to just add the additional parameter AppId to the Register method?
For me it would be ok if the most generic Registration will be used, but if i only register loggers with an AppId are registered for a publisher, the one with the matching AppId should be used.
For example:

When LogMessage is called from App2 with AppId2
OnRegisterTelemetryLogger
- TelemetryLoggersImpl.Register(TelemetryLogger1, Publisher1, NullGuid);
- TelemetryLoggersImpl.Register(TelemetryLogger2, Publisher1, AppId1);
- TelemetryLoggersImpl.Register(TelemetryLogger3, Publisher1, AppId2);

In this case the TelemetryLogger1 with the NullGuid would win, because this is more or less what it does today.

When LogMessage is called from App2 with AppId2
OnRegisterTelemetryLogger
- TelemetryLoggersImpl.Register(TelemetryLogger1, Publisher1, AppId1);
- TelemetryLoggersImpl.Register(TelemetryLogger2, Publisher1, AppId2);
- - TelemetryLoggersImpl.Register(TelemetryLogger3, Publisher1, AppId3);

In this case the TelemetryLogger2 with the AppId2 should be used.

**Comment by IhorHandziuk** [comment]
Hi @JohnnyUndercover , @pri-kise , as explained above to support something like this we need to be able to first populate a collection of interfaces / codeunits, and then select the most appropriate interface / codeunit from that collection.
This is currently not possible. If / when it will become possible, we would definitely revisit this.

**Comment by JohnnyUndercover** [comment]
Do we really need the collection of interfaces?

If i read it right, the event OnRegisterTelemetryLogger is called every time a message is logged (please correct me if i'am wrong) and therefore we only need a logic to store the most explicit impementation.
