### ISSUE TITLE
[Bug]: RSACryptoServiceProvider missing function to initialize an instance of the provider

### ISSUE THREAD

**Issue by JaapMosselman** [microsoft/BCApps#305]
### Describe the issue

The RSACryptoServiceProvider codeunit has a ToXmlString function, to export the key, with or without the private key.
But this codeunit is missing a function  to initialize an instance of the key provider, so ToXmlString with throw an error.

### Expected behavior

I want to be able to initiate a new instance of the RSACryptoServiceProvider, so I can export it with ToXmlString to use it.
So I want to add this function:

    /// <summary>
    /// Initializes a new instance of RSACryptoServiceProvider with the specified key size and returns the key as an XML string. 
    /// </summary>
    /// <param name="KeySize">The size of the key in bits.</param>
    procedure InitializeRSA(KeySize: Integer)
    begin
        RSACryptoServiceProviderImpl.InitializeRSA(KeySize);
    end;

And in "RSACryptoServiceProvider Impl.":

    procedure InitializeRSA(KeySize: Integer)
    begin
        DotNetRSACryptoServiceProvider := DotNetRSACryptoServiceProvider.RSACryptoServiceProvider(KeySize);
    end;

### Steps to reproduce

Call RSACryptoServiceProvider.ToXmlString, it will throw an error that RSACryptoServiceProvider is not instantiated.

### Additional context

I am ready to supply a PR

**Comment by JesperSchulz** [comment]
Just a little more patience. We're currently setting the right automations up between GitHub <-> DevOps. Shortly we'll be ready to triage and approve issues!

**Comment by JesperSchulz** [comment]
Approved! Looking forward to receiving your PR.
