### ISSUE TITLE
[BCIdea]: Add reference "FindBlobsByTags" from the "ABS Client Impl." codeunit  to the "ABS Blob Client" codeunit

### ISSUE THREAD

**Issue by lorenzfleerackers** [microsoft/BCApps#314]
### BC Idea Link

https://experience.dynamics.com/ideas/idea/?ideaid=6c231259-217e-ee11-a81c-000d3ae53364

### Description

I want to filter the blobs by their tags.

The function is allready created in the implementation codeunit but is not added to the client.

![image](https://github.com/microsoft/BCApps/assets/28091845/2a130ce7-da0c-4ae2-a81a-447fcb9e565b)

Can I create the pull request myself?

Kinds regards
Lorenz <br /><br />Internal work item: AB#492545

**Comment by JesperSchulz** [comment]
Just a little more patience. We're currently setting the right automations up between GitHub <-> DevOps <-> BCIdeas. Shortly we'll be ready to triage and approve ideas!

**Comment by JesperSchulz** [comment]
Approved! Please create a PR.
