### ISSUE TITLE
[Bug]: Pull Request Validation does not support all Github Keywords for Work Item Validation

### ISSUE THREAD

**Issue by pri-kise** [microsoft/BCApps#326]
### Describe the issue

Currently we have to write _Fixes_

### Expected behavior

It should be possible to use all GitHub Formats
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved

### Steps to reproduce

Create a PR and use a wrong keyword for linking an issue

### Additional context

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by mazhelez** [comment]
That's a known limitation, to make the parsing a bit more straight-forward.

**Comment by pri-kise** [comment]
@mazhelez maybe it's possible to get the information from the GraphQL Object Property **closingIssuesReferences ** from the [PullRequest](https://docs.github.com/en/graphql/reference/objects#pullrequest)

See:
- https://github.com/orgs/community/discussions/24706
- Example how another GitHub Extension used this in TypeScript
   https://github.com/nearform-actions/github-action-check-linked-issues/blob/main/src/action.js

**Comment by mazhelez** [comment]
That sounds like a good idea! Do you want to give it a try?

**Comment by pri-kise** [comment]
I've seen that @aholstrup1 has an open branch where he is already refactoring and improving this powershell script.
Since I'm not an expert in this area it might make more sense if only one person introduce changes in the same object.
