### ISSUE TITLE
[BC Idea]: Introduce option to suppress zero quantities in sales reports

### ISSUE THREAD

**Issue by miljance** [microsoft/BCApps#327]
### BC Idea Link

https://experience.dynamics.com/ideas/idea/?ideaid=a5457f35-2577-ee11-a81c-000d3ae53364

### Description

Concept:

- A checkbox would be introduced in sales setup named "Do not print lines with 0 quantity".
- A sales report would take this checkbox into account during printout in order to optionally suppress lines that have 0 quantity
- Lines with Type=Comment would not react to this option and should be printed unless "Attached to Line No." has a value.
- When "Attached to Line No." is present for the line with Type=Comment decision whether line should be printed out is inherited from the line to which the comment is attached to.

Background:

- Trough partial invoicing and partial shipping the sales invoices may be created that contain some lines that have quantity 0 and come customers (but not all) want to suppress the printout of those lines.

**Comment by pri-kise** [comment]
This idea is related to something of the BaseApp, therefore the issue should be created at https://github.com/microsoft/BusinessCentralApps (currently private repository).

This repository is currently only for the System Application

**Comment by miljance** [comment]
moved to the BusinessCentralApps repo
