### ISSUE TITLE
[Bug]: User Settings Region Lookup does not preselect current setting (like Language Lookup does)

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/BCApps#351]
### Describe the issue

In User Settings, the Region Lookup does not preselect the current setting in the list like the Language Lookup does. See LanguageImpl.LookupWindowsLanguageId().

### Expected behavior

When selecting a region (Windows Language ID with Language.LookupWindowsLanguageId()), the passed language id should be preselected.

### Steps to reproduce

- Open User Settings
- Click on Lookup Region

Afrikaans is selected, even if another region is current.

### Additional context

-

**Comment by ijesneo611** [comment]
> ### Describe the issue
> In User Settings, the Region Lookup does not preselect the current setting in the list like the Language Lookup does. See LanguageImpl.LookupWindowsLanguageId().
> 
> ### Expected behavior
> When selecting a region (Windows Language ID with Language.LookupWindowsLanguageId()), the passed language id should be preselected.
> 
>111# Steps to reproduce Lodge 111 membership 
> _"Open User Settings"
>eng_usa+-_* Click on Lookup Region
>en-us;esl,nay ASL for English 02ver. 
>English esl_united states is selected, even if another region is current.
> 461;"Additional context_"Footnoted"
en-us;eng_usa",udid*261090**;461#udid

**Comment by ijesneo611** [comment]
jes.int_-"boi"..
