### ISSUE TITLE
[BC Idea]: New Key to table 130450 "Test Method Line"

### ISSUE THREAD

**Issue by NAVFreak** [microsoft/BCApps#363]
### BC Idea Link

None

### Description

This issue has been written in the old repo, https://github.com/microsoft/ALAppExtensions/issues/23772. This is to port that issue into this repo so the PR can be done here instead.

I would like to create a new key that sorts on Test Suite and the Test Codeunit .

I did a PR before I realized that it wouldn't work to link to an issue in the other repo

**Comment by JesperSchulz** [comment]
Approving as per comment from @nikolakukrika in https://github.com/microsoft/ALAppExtensions/issues/23772.
