### ISSUE TITLE
Add "GetSeed" to "Library - Random"

### ISSUE THREAD

**Issue by someC0d3r** [microsoft/BCApps#398]
### Describe the request

When working with random values it could be more helpful if you can output the current seed to the error message by getting it:

![image](https://github.com/microsoft/ALAppExtensions/assets/88825803/48666a79-a756-42b1-be70-64c8b03018d9)

(Or would it be possible to output the current seed by default at the stored error message in the test tool?)

It would help at analyzing errors by knowing which seed got used to reproduce the error (by setting it for example at the beginning of the test and then debug)

### Additional context

see above

**Comment by JesperSchulz** [comment]
@TKapitan, approving issue for your suggested changes. Assigning issue to you 🥳
