### ISSUE TITLE
[Access Request] Sent Emails - NewerThanDate

### ISSUE THREAD

**Issue by GOB-Andrea** [microsoft/BCApps#430]
### Describe the request

Hello everyone,
we use this BC function for opening sent e-mails from interaction log entries:

`Email.OpenSentEmails(Database::"Interaction Log Entry", Rec.SystemId);`

However, the sent emails are only displayed if they are less than one month old, because it is programmed in the OnOpenPage-trigger of the page "Sent Emails":

```
trigger OnOpenPage()
    begin
        NewerThanDate := CreateDateTime(CalcDate('<-30D>', Today()), Time());
        ...
    end;
```

We do not have access to the variable NewerThanDate, nor can we manipulate the variable using a parameter or a function.

Our ideas:

- Add a parameter for the datetime to the function Email.OpenSentEmails
- ... and/or set the flexible datetime yourself based on the creation date of the record provided to the function, so that the page is filtered to at least this datetime.
- ... and/or add an OpenSentEmails-procedure to the page "Sent Emails" and grant us access to the variable "NewerThanDate": changed to protected or via a set-function.

If more information is required, please let us know. 
Thank you very much in advance!

### Additional context

Emails are not intialy displayed if older than one month. We would like to get it more flexible.

**Comment by JesperSchulz** [comment]
Done :-) And I am approving the issue. Please consider performance when suggesting a solution. Loading emails for a long period can take a severe toll on the system.

**Comment by GOB-Andrea** [comment]
@JesperSchulz Perfect! 
I have already watched the video from TechDays and created VM + container, forked the SystemApp and created the changes locally. Perhaps a stupid question, but is it possible to test this in a normal CRONUS database? I would have to uninstall all higher apps (such as Application), which would mean I could no longer use the WebClient... So could you please tell me what is the right way? Or should I just create the PullRequest anyway? 

And one more question: in the video you say that we should assign the issue, but the option is not offered to me. Is that important?
![image](https://github.com/microsoft/BCApps/assets/30338136/d2dfccfe-7c78-48ba-a5ad-7394492035a7)
Video:
![image](https://github.com/microsoft/BCApps/assets/30338136/3ecade9c-7c68-46be-a70f-be06cd6d9a70)
Is there a different way to assign the issue to myself?

Thank you very much!

**Comment by TKapitan** [comment]
@GOB-Andrea For now there is no easy way. In the base app repo there was a script to create local dev env with all apps published as dev extensions, but it's not updated to v24 and new structure yet.

There is a PR (almost ready) - https://github.com/microsoft/BCApps/pull/417 which should give the same script to this repository, so maybe it would be best to wait a few days for this script to be finalized and merged.
