### ISSUE TITLE
[Bug]:  Missing captions in the recurrence schedule

### ISSUE THREAD

**Issue by bc4all** [microsoft/BCApps#432]
### Describe the issue

On the page Recurrence Schedule there are missing captions in the groups MonthlySpecificDay, MonthlyByWeekday, YearlySpecificDay, YearlyByWeekday

### Expected behavior

Captions are added

### Steps to reproduce

Open page reccurence schedule

### Additional context

I already have a code fixed and want to create a pull request for it

**Comment by JesperSchulz** [comment]
Go right ahead!
