### ISSUE TITLE
The file name of AL files should include the id of the object

### ISSUE THREAD

**Issue by rsgilbert** [microsoft/BCApps#446]
### BC Idea Link

https://www.npmjs.com/package/@passioncloud/alrenamer

### Description

Each object in AL has an id that identifies it in BC. 
It would be good if the file name of the AL file included this ID. This makes it easy to know at quick glance which IDs are in use, where gaps are in the IDs and what the next ID is.
Updating these IDs should also be easy

**Comment by JesperSchulz** [comment]
I'm afraid I will have to reject your issue. We've had many discussions on the naming of files after the move to AL, and we've landed on the following best practice: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode.

We are not going to deviate from this best practice based on single preference.

If you are having trouble finding the next available ID, there are some truly excellent tools which can help you! Internally, we've started using @vjekob's [AL Object ID Ninja](https://vjeko.com/2021/09/13/al-object-id-ninja/). It's free of charge and can help you to manage your IDs with ease.

On a different note: Please wait to create PRs, until issues have been approved :-) That way, you won't do work which just will get rejected.

**Comment by rsgilbert** [comment]
Its okay.
But I think the approach I am suggesting is better. 
I implemented the alrenamer tool myself. Its been used very successfully at my company. I am trying to get it to a wider audience.
You get several advantages.
1. The file name is inferred directly from the object. Infact its more or less the first line in the al file. You dont get into scenarios where the object is named differently from the file name. So you can rename the object without worries.
2. You dont have to think of the filename when creating a new al file. Call it whatever you want eg x.al. Later on when you've defined the object, you'll call `alrenamer` and the file will be renamed.
3. The files in a directory become well organised in ascending order.  This is because they are prefixed with the object type (table, page etc) then followed by the object id then the object name.
4. You can incorporate the `alrenamer` command into your devops workflows. For example, you setup a git hook so the files get renamed correctly when a `commit` happens.
5. It's an embrace of the opensource spirit. The `alrenamer` tool is made with love by the community and for the community and not internally by microsoft. Supporting and promoting its use encourages similar tools to be developed.


I dont mind that the PR was rejected. I meant it as a demo. 

Here is a screenshot of how the new file names look like after the change:
![image](https://github.com/microsoft/BCApps/assets/40545352/34dbacbd-32bd-4649-927e-4517565dc329)

Before they looked this:
![image](https://github.com/microsoft/BCApps/assets/40545352/4d0d0ea6-979d-47b2-854f-4bba7c3022d7)

**Comment by TKapitan** [comment]
It's really not needed to change the recommended structure, the ID is not important for developers and most of companies use some kind of automation to handle ID assignments.

All your points are also already covered by the existing VS Code extension (CRS) 

1) Covered
2) Covered
3) The recommended structure is to group objects by functionality, not by object type. It will be also sorted by the ID which is not useful (why do you want to search for something by ID?)
4) This is not a correct approach, files should not be renamed by automation
5) The same as CRS (open source, 200k downloads)

<ObjectNameShort>.<ObjectTypeShortPascalCase>.al

**Comment by JesperSchulz** [comment]
@rsgilbert, please don't create PRs for demos of your internal tools on this repository. It goes against the purpose of our open source ambitions. It's great to have discussions, such as naming discussions, but let's have those discussions the right place.
