### ISSUE TITLE
[Bug]: Azure File Share ListDirectory not returning all files

### ISSUE THREAD

**Issue by ikickicts** [microsoft/BCApps#509]
### Describe the issue

The new Azure File Share functionality introduced in BC23.3 is a great new addition. Unfortunately, the ListDirectory function only returns the first 5000 files in the share and does not implement the Next Marker feature.

### Expected behavior

The API for the Azure File Share indicates that the ListDirectory will return only the first 5000 files in a shared folder, and it returns a NextMarker string in the response if there are further files to be listed. This NextMarker can be used on subsequent requests to retrieve the remaining files

https://learn.microsoft.com/en-us/rest/api/storageservices/list-directories-and-files

I would have expected this NextMarker to be part of the response from ListDirectory BC implementation. (It is present in the ListFileHandles function).

### Steps to reproduce

Create an Azure File Share, and a folder containing more than 5000 items.
Call the AFSFileClient.ListDirectory, and the returned file list contains only the first 5000 items.

        Authorization := StorageServiceAuthorization.UseReadySAS(AzureStorageSetup."Shared Access Signature");
        AFSFileClient.Initialize(AccountName, FileShare, Authorization);
        AFSOperationResponse := AFSFileClient.ListDirectory(FolderName, TempAFSDirectoryContent);

It is not possible to retrieve a list of the remaining files.

### Additional context

No additional context.

**Comment by pri-kise** [comment]
Maybe this can solved similiar to Azure Blob Storage.
See: https://github.com/microsoft/ALAppExtensions/pull/22771

**Comment by JesperSchulz** [comment]
Please go ahead and create a PR to address this issue!

**Comment by MODUSCarstenScholling** [comment]
Now that I know this module already...

**Comment by JesperSchulz** [comment]
> Now that I know this module already...

Real nice effort!
