### ISSUE TITLE
[BC Idea]: Client Credentials authentication for SharePoint.

### ISSUE THREAD

**Issue by pri-kise** [microsoft/BCApps#524]
### BC Idea Link

https://experience.dynamics.com/ideas/idea/?ideaid=15430f25-7f70-ed11-a76e-0003ff45ac6d

### Description

I want to add support for Client Credentials Flow on the Sharepoint Client.

Related Issue: https://github.com/microsoft/ALAppExtensions/issues/22261

### I will provide the implementation for this BC Idea

- [X] I will provide the implementation for this BC Idea 

<br /><br />Internal work item: [AB#457003](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/457003)

**Comment by JesperSchulz** [comment]
Reopening to backport to 24.x.
