### ISSUE TITLE
@Krajzys  @JesperSchulz  Hi, I'm messing about with this in the most recent release and it works great with SAS Token but when I try to use a Shared Key for authentication I run into issues uploading a file to the File Share. I have attached the error. Any ideas? Authentication using shared key works fine for downloading and listing directory requests.

### ISSUE THREAD

**Issue by PJohnstonSysco** [microsoft/BCApps#527]
@Krajzys  @JesperSchulz  Hi, I'm messing about with this in the most recent release and it works great with SAS Token but when I try to use a Shared Key for authentication I run into issues uploading a file to the File Share. I have attached the error. Any ideas? Authentication using shared key works fine for downloading and listing directory requests.

![image](https://github.com/microsoft/BCApps/assets/123634353/72da983e-db4d-4bdb-88ba-9cbe9bd3785f)

_Originally posted by @PJohnstonSysco in https://github.com/microsoft/BCApps/issues/341#issuecomment-1916655574_

**Comment by JesperSchulz** [comment]
Hi @PJohnstonSysco. Issues should be used to suggest fixes in code or new features. They are not meant to be used as support requests. Please use Viva Engage or other forums to ask questions and get help with your problems 😊 Thanks!

**Comment by PJohnstonSysco** [comment]
Hi @JesperSchulz, this is not a request for a new feature., it is a bug. If you try to upload a file to a File Share while authenticated with an Azure Shared Key you will get an error.  This works fine with Blob Storage so should also work with File Shares.

**Comment by JesperSchulz** [comment]
Sure, and if you'd like to take charge and fix that issue, I can approve this GitHub issue to allow you to create a pull request. This just isn't the right place to log bugs for the product team - for that, you must create a support request. And if you've got general questions (as your title indicates), Viva Engage is the place 😊

**Comment by JesperSchulz** [comment]
Maybe the author @Krajzys of the original PR #341 would like to look into this issue for you?

**Comment by JesperSchulz** [comment]
PS: I do get that the process is slightly confusing as it is today, but right now I just need to be very strict about what GitHub issues can be used for, as else we'll get tons of bug reports here, and those we won't be able to deal with. So, just to be clear:

You've found a bug and you want Microsoft to look into it? -> file a support request
You've found a bug (with no customer impact) and you'd like to fix it yourself? -> create a GitHub issue and get it approved
You've got a question? -> Go to Viva Engage or another public forum

Your case here is interesting though, in the sense that you're pointing to an issue introduced in a former PR. I'd admit that our processes don't cater well for this scenario yet. Ideally, I'd like you see going for option 2: fix the issue 😉
