### ISSUE TITLE
Item Tracking Lines Scanning issue

### ISSUE THREAD

**Issue by dennispc** [microsoft/BCApps#529]
When scanning item tracking lines, the page does not go beyond 50-53 lines, without manual intervention.

This can be reproduced by opening item tracking, making lines with 1 in quantity, until down arrow does not go to next line.

This blocks scanning from going to the next line, and is very annoying.

**Comment by JesperSchulz** [comment]
That might just be a product defect! Unfortunately, our GitHub repositories are not suitable to report product defects or change requests. We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:

On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f

Cloud – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
