### ISSUE TITLE
[Bug]: Better repo documentation

### ISSUE THREAD

**Issue by NAVFreak** [microsoft/BCApps#557]
### Describe the issue

Not a bug, but doing bc-idea for repo information would be overkill. Plus @JesperSchulz told to make an issue of it 😉

First time I came to the repo I expected more information about the repo and the system app so I was a little bit surprised when I couldn't find it.  But last week I stumbled across the exactly this information on learn when studying for the developer certification.
So I seized the opportunity to add it there.

### Expected behavior

I want a chapter "Get to know System App" with links to information in [CONTRIBUTING.md](https://github.com/microsoft/BCApps/blob/main/CONTRIBUTING.md)

The chapter should contain these links
![image](https://github.com/microsoft/BCApps/assets/34970096/68541a98-8265-4ef4-9f43-ef920d3e8fc1)

### Steps to reproduce

n/a

### Additional context

Already got a branch ready to turn into a PR.
![image](https://github.com/microsoft/BCApps/assets/34970096/356e94eb-138d-4379-af7c-21b93d3979ae)

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
Great to get contributions to the process part of the project too. Approved!
