### ISSUE TITLE
Testpage with DelayedInsert does not create records sometimes

### ISSUE THREAD

**Issue by DavidFeldhoff** [microsoft/BCApps#561]
Please include the following with each issue:

**1. Describe the bug**
In a testpage that has the DelayedInsert Property set the record is not created everytime. There's no error shown, it simple does not create the record which made it really hard to figure out the problem. Please have a look in the reproduction step as it's not easy to explain (as it's not that obvious)

**2. To Reproduce**

1. Execute the following Test method. 
  - It's fine to just specify the document no.
  - It's fine to specify the document no. and change the Account Type to a different value then the default one.
  - It's fine to specify the document no. and change the Account Type back and forth
  - It's NOT fine to re-enter the current Account Type. Then the record is simply not inserted anymore even there's no error shown. 

``` AL
codeunit 50100 "My Codeunit"
{
    Subtype = Test;

    [Test]
    procedure TestLine()
    var
        GenJournalLine: Record "Gen. Journal Line";
        LibraryAssert: Codeunit "Library Assert";
        PaymentJournal: TestPage "Payment Journal";
    begin
        PaymentJournal.OpenEdit();

        // Just validating the document no. is fine.
        // Record is inserted when leaving the line with .New();
        // Notice that Account Type::Vendor is the default value.
        PaymentJournal."Document No.".SetValue('1234');
        PaymentJournal.New();

        GenJournalLine.SetRange("Document No.", '1234');
        LibraryAssert.IsTrue(GenJournalLine.FindFirst(), 'Gen. Journal Line record not found');
        LibraryAssert.AreEqual(GenJournalLine."Account Type"::Vendor, GenJournalLine."Account Type", 'Account Type not equal');

        // Changing the Account Type to a different value (=Customer) then default (=Vendor) is also fine. 
        // Record is inserted when leaving the line with .New();
        PaymentJournal."Document No.".SetValue('2345');
        PaymentJournal."Account Type".SetValue(GenJournalLine."Account Type"::Customer);
        PaymentJournal.New();

        GenJournalLine.SetRange("Document No.", '2345');
        LibraryAssert.IsTrue(GenJournalLine.FindFirst(), 'Gen. Journal Line record not found when setting value to Customer');

        // Changing the Account Type to Vendor again after once changing it to a different value (=Customer) is also fine.
        // Record is inserted when leaving the line with .New();
        PaymentJournal."Document No.".SetValue('3456');
        PaymentJournal."Account Type".SetValue(GenJournalLine."Account Type"::Customer);
        PaymentJournal."Account Type".SetValue(GenJournalLine."Account Type"::Vendor);
        PaymentJournal.New();

        GenJournalLine.SetRange("Document No.", '3456');
        LibraryAssert.IsTrue(GenJournalLine.FindFirst(), 'Gen. Journal Line record not found when setting value to Customer, then Vendor');
        LibraryAssert.AreEqual(GenJournalLine."Account Type"::Vendor, GenJournalLine."Account Type", 'Account Type not equal');

        // !! Setting the Account Type to Vendor if it was already = Vendor is not fine.
        // Record is NOT inserted anymore after leaving the line with .New()
        PaymentJournal."Document No.".SetValue('4567');
        PaymentJournal."Account Type".SetValue(GenJournalLine."Account Type"::Vendor);
        PaymentJournal.New();

        GenJournalLine.SetRange("Document No.", '4567');
        LibraryAssert.IsTrue(GenJournalLine.FindFirst(), 'Gen. Journal Line record not found when setting value to Vendor only');
    end;
}
```

**3. Expected behavior**
The record has to be inserted still. And in case it's not, there has to be shown an error.

**4. Actual behavior**
Nothing happens. The General Journal Line is simply not created. If there wouldn't be the `Library.IsTrue(GenJournalLine.FindFirst(), ..)` statement, then the test method would simply succeed.

**5. Versions:**

- AL Language: v12.5.914975
- Visual Studio Code: 
Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631
- Business Central: DE Business Central 23.2 (Platform 23.0.14532.0 + Application 23.2.14098.14562)
- List of Visual Studio Code extensions that you have installed:

**Comment by JesperSchulz** [comment]
Hey @DavidFeldhoff. Did you figure out this issue? This issue should not have been transferred here, as this repository isn't a support channel (as you know 😉). I'll hence close it and we'll have to find a different channel to help you. Please reach out to me on Viva Engage.
