### ISSUE TITLE
[Bug]: Cannot create GS-128 barcode 

### ISSUE THREAD

**Issue by ABYSTREK** [microsoft/BCApps#596]
### Describe the issue

Hi, according to the infromation: https://github.com/microsoft/BCApps/tree/main/src/System%20Application/App/Barcode#code128-value-110 
Code-128 supports generating GS-128 barcode.

Also, we have info from the IDAutiomation that MS bought the appropriate font to generate GS-128 barcodes:
"Unfortunately, IDAutomation experience with Azure cloud and Business Central is limited to the information provided here: [Barcode Integration Guide for Microsoft Dynamics 365 | Navision | Business Central (idautomation.com)](https://www.idautomation.com/barcode-integration/microsoft-dynamics/). To our knowledge, Microsoft has licensed our fonts/encoders for GS1-128 barcodes, but how to use the encoding tools provided by Microsoft will be up to them to provide you with instructions. I would recommend that you reach out to Microsoft to inquire as to how to use the IDAutomation tools that come with the cloud products for GS-128."

We tried to generate it, but without any success.

### Expected behavior

Possibility to genere GS-128 barcode like this one:
![image](https://github.com/microsoft/BCApps/assets/136693147/2b1cd0b6-d47e-4e6e-9dd3-2b9e8d4e9ea5)

How we can do this?

### Steps to reproduce

Here is the example code we tried:
![image](https://github.com/microsoft/BCApps/assets/136693147/395bba80-0b6e-4eb5-b35d-0281e82499c4)
![image](https://github.com/microsoft/BCApps/assets/136693147/04e568b5-a61a-4115-baa2-9c323cc3e5c9)
Result:
![image](https://github.com/microsoft/BCApps/assets/136693147/a279dd78-d1a3-47c3-a34a-946f632d3664)

### I will provide a fix for a bug

- [ ] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
@ABYSTREK, are you suggesting to provide a fix for your issue, or are you merely logging a bug?

**Comment by ABYSTREK** [comment]
We managed to achieve the expected result, it turns out it was not a bug, but rather our lack of knowledge. Sorry for disturbance.
