### ISSUE TITLE
[BC Idea]: Page Styles as Enum

### ISSUE THREAD

**Issue by BernhardKloibmueller** [microsoft/BCApps#606]
### BC Idea Link

https://experience.dynamics.com/ideas/idea/?ideaid=95bf2064-f7cf-ee11-92bd-6045bdb614a3

### Description

Please add an Enum which represents the Page Style Expressions similar to the enum of the Cue Styles: enum 9701 "Cues And KPIs Style"

I have already added multiple times the same enum in different Apps to acchieve this but it would he helpful for us developer to have this in the system application.

The new enum should have the values described here:

https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-style-property?wt.mc_id=d365bc_inproduct_alextension

### I will provide the implementation for this BC Idea

- [X] I will provide the implementation for this BC Idea
Internal work item: [AB#502123](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/502123)

**Comment by JesperSchulz** [comment]
Sounds like a fair request 😊 Approved.

**Comment by JesperSchulz** [comment]
Will be implemented by platform. Work was accepted for 2024 wave 2 release and has been assigned to engineering.

**Comment by JesperSchulz** [comment]
Engineering complete. Enum will ship with 2024 wave 2 🥳
