### ISSUE TITLE
[Bug]: BlobClient.PutBlockList() unusable

### ISSUE THREAD

**Issue by Drakonian** [microsoft/BCApps#615]
### Describe the issue

While working with Azure Blob Services API module I found some inconsistencies and after analyzing it I want to share it.

The point is that PutBlockList cannot be used now.
https://github.com/microsoft/BCApps/blob/cd59daa4fe99bc60133c5c6eb45beb3d6f9428a6/src/System%20Application/App/Azure%20Blob%20Services%20API/src/ABSBlobClient.Codeunit.al#L772

According to the documentation:
![image](https://github.com/microsoft/BCApps/assets/16802407/e1387f34-1ea8-40e9-af6f-7dd74fa4e533)

But at the same time PutBlock operation is not represented in the ABSBlobClient codeunit. Which makes it impossible to use the PutBlockList() method. 

What is interesting is that in the implementation this method already exists and all we have to do is add it to the ABSBlobClient interface. 
https://github.com/microsoft/BCApps/blob/cd59daa4fe99bc60133c5c6eb45beb3d6f9428a6/src/System%20Application/App/Azure%20Blob%20Services%20API/src/ABSClientImpl.Codeunit.al#L652

In addition, I think that the PutBlockList() method lacks the BlobName parameter because it is not clear at what point this name is implicitly received by ABSOperationPayload.
https://github.com/microsoft/BCApps/blob/cd59daa4fe99bc60133c5c6eb45beb3d6f9428a6/src/System%20Application/App/Azure%20Blob%20Services%20API/src/ABSClientImpl.Codeunit.al#L676

### Expected behavior

This should work so that we can make multiple PutBlocks with a unique identifier in Base64 and then modify/add the blocks we need to get one initial Blob consisting of these blocks.

As example:

Put first uncommitted block:
```
curl --location --request PUT 'https://beedynamics.blob.core.windows.net/cronususainc/1/test1.txt?{SAS}&comp=block&blockid=MQ%3D%3D' \
--header 'x-ms-blob-type: BlockBlob' \
--header 'Content-Type: text/plain' \
--data 'part1'
```

Put second uncommitted block:
```
curl --location --request PUT 'https://beedynamics.blob.core.windows.net/cronususainc/1/test1.txt?{SAS}&comp=block&blockid=Mg%3D%3D' \
--header 'x-ms-blob-type: BlockBlob' \
--header 'Content-Type: text/plain' \
--data 'part2'
```

Commit two blocks as one Blob:
```
curl --location --request PUT 'https://beedynamics.blob.core.windows.net/cronususainc/1/test1.txt?{SAS}&comp=blocklist' \
--header 'Content-Type: application/xml' \
--data '<BlockList>  
  <Uncommitted>MQ==</Uncommitted>
  <Uncommitted>Mg==</Uncommitted>
</BlockList>  '
```

### Steps to reproduce

Try to use PutBlockList

### Additional context

I originally wanted to send a PR with a fix, but judging by the rules it has to be negotiated in Issue first. And yes I know AppendBlock works in a similar way and it works fine.

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by PaulFurlet** [comment]
> AppendBlock works in a similar way and it works fine.
It produces different [type of blob](https://learn.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs). It would help if we could convert easily afterwards. But once the blob has been created, its type cannot be changed, and it can be updated only by using operations appropriate for that blob type, so it is not easiy convertable, only downloading and uploading with different type, which is negating all efforts we are trying to use here.

Thank you for opening this ticket, I was looking for solution and you managed to get there first :)

**Comment by PaulFurlet** [comment]
for reference, [my Yammer post](https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=2614962368364544)
