### ISSUE TITLE
[Bug]: GetXHttpMethod returns no value in 9107 "SharePoint Http Content"

### ISSUE THREAD

**Issue by fvet** [microsoft/BCApps#666]
### Describe the issue

The codeunit 9107 "SharePoint Http Content" contains a setter / getter functions for XHttpMethod.

However, the SetXHttpMethod does not properly set the value, resulting in GetXHttpMethod returning an empty value.

### Expected behavior

```
procedure SetXHttpMethod(XHttpMethodValue: Text)
    begin
        XHttpMethodValue := XHttpMethodValue;
    end;
```

should be changed by

```
procedure SetXHttpMethod(XHttpMethodValue: Text)
    begin
        XHttpMethod:= XHttpMethodValue;
    end;
```

resulting in GetXHttpMethod returning the correct value

```
procedure GetXHttpMethod(): Text;
    begin
        exit(XHttpMethod);
    end;
```

### Steps to reproduce

- Call SharePointHttpContent.SetXHttpMethod('MERGE'); 
- SharePointRequestHelper.Post(SharePointUriBuilder, SharePointHttpContent);

Below code does not add a X-HTTP-Method header ...
```
if SharePointHttpContent.GetXHttpMethod() <> '' then
            Headers.Add('X-HTTP-Method', SharePointHttpContent.GetXHttpMethod());
```

### Additional context

I can provide a fix, but have no time to write any tests

### I will provide a fix for a bug

- [ ] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
We'll take that fix - thanks 😊 Approved.
