### ISSUE TITLE
[Bug]: When using Azure Shared Key to load files to Azure File Share you are presented with an Authentication error

### ISSUE THREAD

**Issue by PJohnstonSysco** [microsoft/BCApps#685]
### Describe the issue

When you try to load a file to an Azure File Share while connected using an Azure Share Key you are presented with an authentication error. You do not get the same error when using the List File function or Download Files

### Expected behavior

The file should be loaded to the Azure File Share without error

### Steps to reproduce

Use an Azure Shared Key when authenticating with the New Azure File module and try to upload a file to the File Share

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
Sounds like a bug! Of course approved 😊

**Comment by Drakonian** [comment]
@PJohnstonSysco If you don't have time, I can do the fix

**Comment by PJohnstonSysco** [comment]
@Drakonian I have got caught up with other things. If you have time that would be great
