### ISSUE TITLE
[Bug]: Rest Client - GetAsJson gives "The data does not represent a valid JSON token." on 204 No Content

### ISSUE THREAD

**Issue by jorispoppe** [microsoft/BCApps#744]
### Describe the issue

In the Rest Client I have the following issue:

I have a call that sends back Json as a 200 response, but when no information is found the api sends a 204 response.

When I use the Rest Client GetAsJson function:
- the 200 response works fine and I have the information from the API in the JsonToken
- the 204 response gives an error  "The data does not represent a valid JSON token." 

### Expected behavior

The expected behavior would be that there is no error and that we would be able to check the JsonToken (with IsObject, IsArray, IsValue) if we have the 204 response.

The code that gives the error is in `codeunit 2355 "Http Content Impl."`

```
procedure AsJson() ReturnValue: JsonToken
begin
    ReturnValue.ReadFrom(AsText());
end;
```

A possible solution would be:

```
procedure AsJson() ReturnValue: JsonToken
var
    JsonText: Text;
begin
    JsonText := AsText();
    if JsonText <> '' then
        ReturnValue.ReadFrom(JsonText);
end;
```

### Steps to reproduce

Example API call is the BC Admin API with the upgrade information of an environment:

https://api.businesscentral.dynamics.com/admin/v2.20/applications/BusinessCentral/environments/{{BCEnvironment}}/upgrade

When an upgrade is available, the GetAsJson gives the JsonToken back, when no upgrade available, then the API gives a 204 result and then the AsJson method gives the error.

### Additional context

If my solution would be approved I can make the pull request, but I'm new to writing tests and executing them.

### I will provide a fix for a bug

- [ ] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
That does sound very reasonable to me - however, I'm not much of an expert in this area. @ajkauffmann, would you have an opinion on the suggested change?

**Comment by Drakonian** [comment]
I can do the fix if it's okay with anyone

**Comment by ajkauffmann** [comment]
I've given it some thought.  In the first place I was thinking, why not check the status code first? For example check if status is 204 and in that case don't try to read the content.
But on second thought, there are more statuses that don't reply content, like 202 and others. And web services may have a different implementation on status 201 Created.
So after all, I think the proposed solution is the best option. In case there is content, it is still being checked if it is valid JSON. In case of no content, you don't get an error message.
I'm planning to create a PR with some improvements, I can take it as well. Should be ready in April.

**Comment by Drakonian** [comment]
@ajkauffmann 
Basically if you find the time in April I will leave it for you, you know this module better :)
