### ISSUE TITLE
[BC Idea]: Add PUT method to Graph API Module

### ISSUE THREAD

**Issue by devgar** [microsoft/BCApps#748]
### BC Idea Link

https://experience.dynamics.com/ideas/idea/?ideaid=160fc653-dde1-ee11-a73e-002248504629

### Description

Currently Graph API module's "Graph Client" Codeunit has Get, Post, Patch and Delete Methods but lacks a PUT method which is also required for some microsoft graph requests.

It also lacks OPTIONS and HEAD methods which are common HTTP Methods but I don't realy know if they are common on Microsoft Graph.

I propose to include the PUT method, I have an initial implementation which could be included through pull request on GitHub.

### I will provide the implementation for this BC Idea

- [X] I will provide the implementation for this BC Idea

**Comment by duichwer** [comment]
I'm really looking forward to this PR.
I know that there are missing some parts in the Microsoft Graph Module, but I didn't had the time to make this module complete.

**Comment by JesperSchulz** [comment]
Based on @duichwer's comment, this seems to be something we want 😉 Approved.

**Comment by duichwer** [comment]
@devgar I don't know any endpoints of the Microsoft Graph API that support HEAD or OPTIONS request.
If you find some then please show them and they can be added, too.
The general documentation doesn't mention them
https://learn.microsoft.com/en-us/graph/use-the-api#http-methods

**Comment by devgar** [comment]
Excellent, In what release version will it be available in?

**Comment by JesperSchulz** [comment]
> Excellent, In what release version will it be available in?

Unfortunately the change came in too late to be part of the April release (24.0). By default your changes will hence release with the next major (25.0 in October), but if you need them sooner, we can backport your changes to release with version 24.1 in May.

**Comment by devgar** [comment]
It would feel great if it fits in 24.1 or 24.2

**Comment by JesperSchulz** [comment]
You got it! I'll make sure it releases with 24.1 🙂

**Comment by JesperSchulz** [comment]
Reopening to backport to 24.x.
