### ISSUE TITLE
[Bug]: the SUPPORT.md file in this repo has not been filled out

### ISSUE THREAD

**Issue by jeffwilcox** [microsoft/BCApps#749]
While this template has a lot of information about not filing a product support issue, the `SUPPORT.md` file in this repo is still the default template, and should be updated by the repository owners to better include this support statement, too.

See also: https://github.com/microsoft/BCApps/blob/main/SUPPORT.md

**Comment by JesperSchulz** [comment]
Very true! Thanks for pointing this out. @mazhelez / @aholstrup1, will you look into this?
