### ISSUE TITLE
[BC Idea]: Improve Microsoft Graph Module with OData Query Parameters

### ISSUE THREAD

**Issue by pri-kise** [microsoft/BCApps#802]
### BC Idea Link

https://experience.dynamics.com/ideas/idea/?ideaid=e0452d86-70e7-ee11-a73e-002248504629

### Description

We cannot specify ODataQuery Parameter as optional paramter.

This should be added to work appropriate with microsoft graph endpoints.

### I will provide the implementation for this BC Idea

- [X] I will provide the implementation for this BC Idea
Internal work item: [AB#522447](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/522447)

**Comment by JesperSchulz** [comment]
Reopening as the code is getting backported to 24.x as well.

**Comment by JesperSchulz** [comment]
All done.
