### ISSUE TITLE
[Bug]: Toggle Expand is not working

### ISSUE THREAD

**Issue by FSchneiderYav** [microsoft/BCApps#814]
### Describe the issue

The Expand of a line is not working in BC24. Expand in the title(1) is working, but expand for a single line(2) is resulting in a loading screen
![image](https://github.com/microsoft/BCApps/assets/47736215/6fadaab9-2c3c-4611-ad51-a98e4cfb587a)

### Expected behavior

Expand for a single line is working.

### Steps to reproduce

Open page AL Test Tool.
Get Test Codeunits.
Go to a line with Line Type = Codeunit and klick on the arrow before Codeunit.
![image](https://github.com/microsoft/BCApps/assets/47736215/0e092e57-65fa-469d-958d-1b77993864c4)

### I will provide a fix for a bug

- [ ] I will provide a fix for a bug

**Comment by Drakonian** [comment]
I tried reproducing in the current main BC25 and could not reproduce such a problem. Are you sure you didn't miss anything in the description and you don't have any customization on this page? Unfortunately I can't check for BC24 right now.

**Comment by JesperSchulz** [comment]
@FSchneiderYav, if you can reproduce, can find the root cause and are willing to provide a fix, I'd be happy to approve. I too am not able to reproduce in the latest version, but maybe I'm just doing something wrong...

**Comment by FSchneiderYav** [comment]
I have created a new container with a new BC24 version. It is working now.
