### ISSUE TITLE
[BC Idea]: Remove NonDebuggable property from several parts of the system application

### ISSUE THREAD

**Issue by pri-kise** [microsoft/BCApps#875]
### BC Idea Link

https://experience.dynamics.com/ideas/idea/?ideaid=5c138a47-a3f2-ee11-a73d-6045bdb71da1

### Description

Currently there are still a lot of procedures that doesn't allow debugging.

This might make sense for Authorization and user based information, but sometimes the NonDebuggable property seems to forgotten and should be removed.

Since it's difficult to do this by my own without Microsoft beeing involed I'd like to discuss the details before removing the NonDebuggable property.

here some example

```al
//codeunit 9350 "Graph Client"
    var
        [NonDebuggable] //Makes it impossible to debug the implementation
        GraphClientImpl: Codeunit "Graph Client Impl.";
```

```al
//codeunit 7803 "Azure Functions Impl"
    [NonDebuggable]
    procedure SendGetRequest(AzureFunctionAuthentication: Interface "Azure Functions Authentication"; QueryDict: Dictionary of [Text, Text]): Codeunit "Azure Functions Response"
    begin
        exit(Send(AzureFunctionAuthentication, Enum::"Http Request Type"::GET, QueryDict, '', ''));
    end;
```

### I will provide the implementation for this BC Idea

- [X] I will provide the implementation for this BC Idea
Internal work item: [AB#524277](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524277)

**Comment by JesperSchulz** [comment]
@pri-kise, I do think this is much easier to do in a "case by case" fashion. You present the properties you want to remove, and we review them. I'll approve this idea on those terms. An issue can be linked to many PRs, so this doesn't have to happen in one go.

**Comment by JesperSchulz** [comment]
Reopening, as more PRs are coming.
