### ISSUE TITLE
[BC Idea]: Action in Page 2508 to Extension Management

### ISSUE THREAD

**Issue by JulianTillmann** [microsoft/BCApps#977]
### BC Idea Link

https://experience.dynamics.com/ideas/idea/?ideaid=7a60b923-4f01-ef11-a73c-0022484ddea9

### Description

When uploading a PTE we have to refresh the "Extension Installation Status" page, which the is the main page in the browser. When we want to navigate back to the "installed extensions" page you have to search again.

the idea is a simple navigation button to open the page "2500 "Extension management"

### I will provide the implementation for this BC Idea

- [X] I will provide the implementation for this BC Idea
Internal work item: [AB#527490](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527490)

**Comment by TKapitan** [comment]
Maybe the better idea would be to add the action "Refresh" that is available on the deployment status detail page? This refresh will refresh only the record status and you will still be able to get back to the previous page.

When I need to deploy something manually, I'm always opening details and refreshing the status using this refresh action.

**Comment by JulianTillmann** [comment]
@TKapitan 
¿Por Qué No Los Dos?

if I'm editing the page anyway I could do both

**Comment by JesperSchulz** [comment]
Sure! Let's do this! Approved 😊
