### ISSUE TITLE
[Bug]: SecretText implementation blocks/limits public key retrieval

### ISSUE THREAD

**Issue by PeterConijn** [microsoft/BCApps#987]
### Describe the issue

Disclaimer: I am not a cryptographer, so I may be understanding this wrong. 

I was mucking about in the [RSACryptoProvider codeunit](https://github.com/microsoft/BCApps/blob/main/src/System%20Application/App/Cryptography%20Management/src/DSACryptoServiceProvider.Codeunit.al) when I noticed that the procedures were all obsoleted in favor of procedures using SecretText, which makes sense. However, this also impacts the retrieval of the public key, which - as I understand it - is specifically meant to be shareable.

Should we not retain a ToXmlString procedure that retrieves the public key (and **only** the public key) as a regular text, so that it can more easily be shared? The [DSACryptoProvider codeunit](https://github.com/microsoft/BCApps/blob/main/src/System%20Application/App/Cryptography%20Management/src/DSACryptoServiceProvider.Codeunit.al), conversely, still allows both public and private key to be retrieved as plain text.

### Expected behavior

I would expect a GetPublicKeyAsXmlString(): Text procedure in the RSACryptoProvider that takes no arguments and returns the public key as a text, akin to the obsoleted implementation of ToXmlString.

I would also expect the DSACryptoProvider to follow a similar pattern: one procedure with a text return for public key and one with secrettext for either public or public+private.

### Steps to reproduce

1. Retrieve a public key using the new implementation that uses secret text
2. Try to share that key with a third party

### Additional context

I just happened to notice this and my (albeit limited) experience with signing and cryptology thought it was strange. 

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
@darjoo / @WaelAbuSeada, could you triage this issue, please?

**Comment by darjoo** [comment]
This can be approved as it's only about the public key and not the private key in plain text.
